/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const Time = IDL.Int;
export const LeaderboardEntry = IDL.Record({
  'total' : IDL.Nat,
  'name' : IDL.Text,
  'score' : IDL.Nat,
  'timestamp' : Time,
  'category' : IDL.Text,
  'percentage' : IDL.Float64,
});
export const Question = IDL.Record({
  'id' : IDL.Text,
  'categoryId' : IDL.Text,
  'text' : IDL.Text,
  'correctAnswer' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'clearLeaderboard' : IDL.Func([], [], []),
  'forceReinitialize' : IDL.Func([], [], []),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getQuestionById' : IDL.Func([IDL.Text], [Question], ['query']),
  'getQuestionsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'submitScore' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const Time = IDL.Int;
  const LeaderboardEntry = IDL.Record({
    'total' : IDL.Nat,
    'name' : IDL.Text,
    'score' : IDL.Nat,
    'timestamp' : Time,
    'category' : IDL.Text,
    'percentage' : IDL.Float64,
  });
  const Question = IDL.Record({
    'id' : IDL.Text,
    'categoryId' : IDL.Text,
    'text' : IDL.Text,
    'correctAnswer' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'clearLeaderboard' : IDL.Func([], [], []),
    'forceReinitialize' : IDL.Func([], [], []),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getQuestionById' : IDL.Func([IDL.Text], [Question], ['query']),
    'getQuestionsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'submitScore' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };