/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'id' : string, 'name' : string }
export interface LeaderboardEntry {
  'total' : bigint,
  'name' : string,
  'score' : bigint,
  'timestamp' : Time,
  'category' : string,
  'percentage' : number,
}
export interface Question {
  'id' : string,
  'categoryId' : string,
  'text' : string,
  'correctAnswer' : bigint,
  'options' : Array<string>,
}
export type Time = bigint;
export interface _SERVICE {
  'clearLeaderboard' : ActorMethod<[], undefined>,
  'forceReinitialize' : ActorMethod<[], undefined>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getQuestionById' : ActorMethod<[string], Question>,
  'getQuestionsByCategory' : ActorMethod<[string], Array<Question>>,
  'initialize' : ActorMethod<[], undefined>,
  'submitScore' : ActorMethod<[string, bigint, bigint, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];