/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const Entry = IDL.Record({
  'id' : IDL.Nat,
  'data' : IDL.Text,
  'likes' : IDL.Nat,
  'timestamp' : Time,
  'isPublic' : IDL.Bool,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addToCollection' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'createEntry' : IDL.Func([IDL.Text, IDL.Text], [Entry], []),
  'createUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteEntry' : IDL.Func([IDL.Nat], [], []),
  'getAllEntries' : IDL.Func([], [IDL.Vec(Entry)], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
  'getEntry' : IDL.Func([IDL.Nat], [Entry], []),
  'getUser' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], []),
  'getUserEntries' : IDL.Func([IDL.Text], [IDL.Vec(Entry)], []),
  'isPublic' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'likeEntry' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'removeFromCollection' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'saveImage' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
  'saveVideo' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
  'updateEntry' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const Entry = IDL.Record({
    'id' : IDL.Nat,
    'data' : IDL.Text,
    'likes' : IDL.Nat,
    'timestamp' : Time,
    'isPublic' : IDL.Bool,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addToCollection' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'createEntry' : IDL.Func([IDL.Text, IDL.Text], [Entry], []),
    'createUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteEntry' : IDL.Func([IDL.Nat], [], []),
    'getAllEntries' : IDL.Func([], [IDL.Vec(Entry)], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
    'getEntry' : IDL.Func([IDL.Nat], [Entry], []),
    'getUser' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], []),
    'getUserEntries' : IDL.Func([IDL.Text], [IDL.Vec(Entry)], []),
    'isPublic' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'likeEntry' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'removeFromCollection' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'saveImage' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
    'saveVideo' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
    'updateEntry' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };